### ISSUE TITLE
コードブロック内のテキストに絵文字を含むと、本文の文字列としてカウントされてしまう？

### ISSUE THREAD

**Issue by mono0926** [swift-tweets/swtws#1]
1つめだとOKで、2つめだとエラーが発生しました(条件さぐるために弄ったので文章・コード内容自体は気にしないでください):

---

以上のようにStringから直接取得したIndexはcharactersのIndex操作に使えるので、Indexはcharactersを介さずに済み少しシンプルな記述とできます。

```swift:count2.swift
"1️⃣"
```

---

以上のようにStringから直接取得したIndexはcharactersのIndex操作に使えるので、Indexはcharactersを介さずに済み少しシンプルな記述とできます。

```swift:count2.swift
"1️⃣2️⃣3️⃣4️⃣5️⃣"
```

---

上の例で後者だと、以下のエラーになってしまいました。コードブロック内のテキストはgist URLになるので、文字数に影響しない、というのが正しいはずですよね？？

```
➜  swtws-manuscript git:(master) ✗ swtws manuscript.tw --count
tooLong("以上のようにStringから直接取得したIndexはcharactersのIndex操作に使えるので、Indexはcharactersを介さずに済み少しシンプルな
記述とできます。\n\n```swift:count2.swift\n\"1️⃣2️⃣3️⃣4️⃣5️⃣\"\n``` #swtws", nil, 141)
```

Pull Request投げようかと思いましたが、どこが該当箇所かサクッと分からず少し時間かかりそうだったので、とりあえずIssueあげておきます。
( https://github.com/swift-tweets/tweetup-kit にIssue作るか迷いつつ)

---

> コードブロック内のテキストはgist URLになるので、文字数に影響しない、というのが正しいはずですよね？？

ちなみに以下でもエラーは発生せずでした。

---

以上のようにStringから直接取得したIndexはcharactersのIndex操作に使えるので、Indexはcharactersを介さずに済み少しシンプルな記述とできます。

```swift:count2.swift
"ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ"
```

**Comment by koher** [comment]
ありがとうございます。絵文字が正しく反映されていない気がするので、ファイルの形で送っていただけると助かります。

**Comment by mono0926** [comment]
@koher 

> 絵文字が正しく反映されていない気がするので、ファイルの形で送っていただけると助かります。

確かに、テキストとしての貼り付けに苦労しました。

こちらです:
[sample.tw.zip](https://github.com/swift-tweets/swtws/files/695326/sample.tw.zip)

**Comment by koher** [comment]
修正しました！ TweetupKit のバグでした。

同じ引数を何度も書くのが面倒で `internal` な `extension` を生やして置き換えた箇所で、 1 箇所置き換えが漏れていて、 `extension` のバグフィックスをしたのにその 1 箇所だけ反映されていなかったことが原因でした。

https://github.com/swift-tweets/tweetup-kit/commit/0d007d82f0ac9bc2d9235de131fbe52531cb0011

ご報告ありがとうございました！

**Comment by koher** [comment]
swtws 側は修正はないので、

```bash
swift build --clean
swift build --clean dist
```

で中間生成物を消してからリビルドして下さい。更新されたライブラリが落ちてきます。

**Comment by mono0926** [comment]
@koher 

ありがとうございます、問題無く動くようになりました 🎉
